version: "3"
services:
  gibbon:
    image: tendomart/gibbon:latest
    container_name: gibbon
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - my-gibbon:/var/www/gibbon.local/
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3307'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
  my-gibbon:
Viewed
Original file line number 	Original file line 	Diff line number 	Diff line change
@@ -0,0 +1,42 @@
version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'gibbondb'      
      MYSQL_USER: 'gibbon'      
      MYSQL_PASSWORD: 'gibbon-password'      
      MYSQL_ROOT_PASSWORD: 'SuperSecretPassword'
    ports:      
      - '3306:3306'
    expose:
      - '3306'      
    volumes:
      - gibbon-db:/var/lib/mysql
      - ./gibbon.sql:/docker-entrypoint-initdb.d/gibbon.sql
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '--silent', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 30s
      timeout: 20s
      retries: 20
  gibbon:
    image: gibbon/gibbon
    build: .
    restart: always
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'gibbondb'
      MYSQL_USER: 'gibbon'
      MYSQL_PASSWORD: 'gibbon-password'
    ports:
      - "8080:80"
    volumes:
      - gibbon-uploads:/var/www/html/uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  gibbon-db:
  gibbon-uploads:
102 changes: 102 additions & 0 deletions 102
docker-gibbon-entrypoint
